name = "QbitMPS"
uuid = "2d475602-0786-4526-8650-52c1196694c8"
authors = ["rbn <drbn.rbn@tutanota.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Circuits = "0891af99-d974-44fe-bb1f-8df04484ce9a"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
